language: ruby
rvm:
  - 2.5.0
  - 2.6.0
  - 2.7.0
  - 3.0.0
  - 3.1.0

# Bundler 1.13 added support for `ruby RUBY_VERSION` in the Gemfile
before_install: gem install bundler -v '1.17.3'

sudo: false
notifications:
  email:
    - toolbag@gmail.com
    - christian@minimul.com
