name: Approve PRs
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
jobs:
  auto-approve:
    runs-on: ubuntu-latest
    if: (!github.event.pull_request.draft)
    permissions:
      pull-requests: write
    steps:
      - name: 'Auto approve'
        uses: hmarr/auto-approve-action@v3
        if: github.actor == 'thestelz' && contains(github.event.pull_request.labels.*.name, 'auto-approve')
